export const SET_CHAT_INITIALIZED = 'SET_CHAT_INITIALIZED';
export const SET_CHAT_LOADING = 'SET_CHAT_LOADING';
export const SET_CHAT_LOADED = 'SET_CHAT_LOADED';
export const SET_CHAT_ERROR = 'SET_CHAT_ERROR';
