export const SET_CHAT_INITIALIZED = 'SET_CHAT_INITIALIZED';
export const SET_CHAT_LOADING = 'SET_CHAT_LOADING';
export const SET_CHAT_LOADED = 'SET_CHAT_LOADED';
export const SET_CHAT_ERROR = 'SET_CHAT_ERROR';
export const RESET_CHAT_ERROR = 'RESET_CHAT_ERROR';
export const RESET_CHAT = 'RESET_CHAT';

export const SET_CURRENT_USER_MESSAGE = 'SET_CURRENT_USER_MESSAGE';
export const SET_CURRENT_BOT_MESSAGE = 'SET_CURRENT_BOT_MESSAGE';
